main_app/urls.py
from django.urls import path
from . import views

app_name = 'main_app'

urlpatterns = [
    # Main paths
    path('', views.home, name="home"),
    path('product/<slug:slug>/', views.product, name="product"),
    path('service/', views.services, name="services"),
    path('service/<slug:slug>/', views.service, name="service"),
    path('requests/', views.requests, name="requests"),
    path('requests/<slug:slug>', views.request, name="request"),

    # Company Register Paths
    path('dashboard/company/', views.register_company_view, name="company_view"),
    path('dashboard/company/create', views.register_company_create, name="company_create"),

    # Profile paths
    path('company/<slug:slug>/', views.company, name="company"),
    path('profile/<slug:slug>/', views.profile, name="profile"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('historic/', views.historic, name="historic"),

    # Shopping Cart paths
    path('shopping/', views.shopping_cart, name="shopping"),
    path('shopping/delete', views.shopping_delete, name="shopping_delete"),
    path('shopping/edit', views.shopping_edit, name="shopping_edit"),
    
    # Register / Login / Logout paths
    path('register/', views.register_view, name="register"),
    path('register/create/', views.register_create, name="create"),
    path('login/', views.login_view, name="login"),
    path('login/validate', views.login_validate, name='validate'),
    path('logout/', views.logout_view, name="logout"),

    # Other paths
    path('about/', views.about_us, name="about"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_app/forms/add_to_cart.py
from django import forms
from ..models import ShoppingCart

class AddToCartForm(forms.ModelForm):
    
    class Meta:
        model = ShoppingCart
        fields = ("client", "product", "amount", "finalPrice")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)





main_app/forms/login.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(
        label='Usuário',
        widget=forms.TextInput(attrs={
            'placeholder': 'Insira seu nome de usuário'
        })
    )
    password = forms.CharField(
        label='Senha',
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Insira sua senha'
        })
    )

main_app/forms/register_company.py
import requests
from django import forms
from ..models import Companies, Address, UserProfile
from django.core.exceptions import ValidationError
from utils import form_utils as fu
import PIL


class RegisterCompanyForm(forms.Form):

    # Company Fields
    CNPJ = forms.CharField(
        label='CNPJ',
        validators=[fu.valid_cnpj],
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Ex.: "01.234.567/8910-11."'
            }
        )
    )
    legalName = forms.CharField(
        label='Razão Social',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Razão social da empresa'
            }
        )
    )
    businessName = forms.CharField(
        label='Nome Fantasia',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Nome fantasia da empresa'
            }
        )
    )

    # Address Fields
    CEP = forms.CharField(
        label='CEP',
        validators = [fu.valid_cep],
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Ex.: "12345-678"'
            }
        )
    )
    number = forms.IntegerField(
        label='Número',
        widget=forms.NumberInput(
            attrs={
                'placeholder': 'Número do endereço'
            }
        )
    )
    complement = forms.CharField(
        label='Complemento',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Complemento do endereço'
            }
        )
    )

    # More Company Fields
    description = forms.CharField(
        label='Descrição',
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Descrição da empresa'
            }
        )
    )
    profilePic = forms.ImageField(
        label='Foto de Perfil',
        required=False,
        widget=forms.FileInput()
    )

    def clean_CNPJ(self):
        data = self.cleaned_data.get('CNPJ')
        url = f"https://publica.cnpj.ws/cnpj/{fu.clear_data(data)}"
        response = requests.get(url)

        if response.status_code != 200:
            raise ValidationError(
                'CNPJ inválido',
                code='invalid'
            )

        return fu.clear_data(data)
    
    def clean_CEP(self):
        data = self.cleaned_data['CEP']
        data = fu.clear_data(data)
        url = f'https://viacep.com.br/ws/{data}/json/'
        response = requests.get(url)

        if response.status_code != 200:
            raise ValidationError('Tente novamente mais tarde')
        
        if 'erro' in response.json():
            raise ValidationError(
                'CEP inválido',
                code='invalid'
            )

        return data
    
    def save(self, user):
        cep = self.cleaned_data['CEP']
        number = str(self.cleaned_data['number'])
        complement = self.cleaned_data['complement']
        address = Address.objects.filter(
            CEP=cep,
            number=number,
            complement=complement
        ).first()

        if not address:
            url = f'https://viacep.com.br/ws/{cep}/json/'
            response = requests.get(url).json()

            address = Address.objects.create(
                CEP=cep,
                state=response['uf'],
                city=response['localidade'],
                neigborhood=response['bairro'],
                streetAddress=response['logradouro'],
                number=number,
                complement=complement
            )

        cnpj = self.cleaned_data['CNPJ']
        legal_name = self.cleaned_data['legalName']
        business_name = self.cleaned_data['businessName']
        profile_pic = self.cleaned_data['profilePic']
        description = self.cleaned_data['description']
        
        company = Companies.objects.create(
            CNPJ=cnpj,
            legalName=legal_name,
            businessName=business_name,
            slug=fu.create_slug(legal_name),
            profilePic=profile_pic,
            description=description,
            owner=user,
            address=address,
            isPartner=True,
        )
        print('salvei')

        return company


main_app/views.py
from django.http.response import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.models import User
from main_app.models import Products, Companies, SocialMedia, Services, UserProfile, ShoppingCart, Employee, Requests
from utils.pagination import make_pagination
from .forms import LoginForm, SignUpForm, AddToCartForm, RegisterCompanyForm

import os

PER_PAGE = int(os.environ.get('PER_PAGE', 30))

# Create your views here.
@login_required(login_url='main_app:login', redirect_field_name='next')
def home(request):

    search_term = request.GET.get('q', '').strip()

    if not search_term:
        products = Products.objects.filter(
            company__isPartner=True
        ).order_by('-id')
        additional_query_string = ''
    else:
        products = Products.objects.filter(
            Q(name__icontains=search_term) |
            Q(details__icontains=search_term),
            company__isPartner=True,
        ).order_by('-id')
        additional_query_string = f'&q={search_term}'

    if request.method == 'POST':
        form = AddToCartForm(request.POST)
        if form.is_valid():
            existing_item = ShoppingCart.objects.filter(
                client=form.cleaned_data['client'],
                product=form.cleaned_data['product']
            ).exists()
            if not existing_item:
                form.save()
    else:
        form = AddToCartForm()
    form = AddToCartForm()

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    page_object, pagination_range = make_pagination(request, products, PER_PAGE)

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'additional_url_query': additional_query_string,
        'form': form,
        'pagination_range': pagination_range,
        'products': page_object, 
        'products_amount': products_amount,
        'search_term': search_term,
        'show_products': True,
        'user_profile': user_profile,
    }

    return render(request=request, template_name='main/pages/home.html', context=context)


@login_required(login_url='main_app:login', redirect_field_name='next')
def product(request, slug):
    product = get_object_or_404(
        Products, slug=slug
    )

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    if request.method == 'POST':
        form = AddToCartForm(request.POST)
        if form.is_valid():
            existing_item = ShoppingCart.objects.filter(
                client=form.cleaned_data['client'],
                product=form.cleaned_data['product']
            ).exists()
            if not existing_item:
                form.save()
    else:
        form = AddToCartForm()

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'form': form,
        'product': product,
        'products_amount': products_amount,
        'user_profile': user_profile,
        }

    return render(request=request, template_name='main/pages/product.html', context=context)


@login_required(login_url='main_app:login', redirect_field_name='next')
def services(request):

    search_term = request.GET.get('q', '').strip()

    if not search_term:
        services = Services.objects.filter(
            company__isPartner=True
        ).order_by('-id')
        additional_query_string = ''
    else:
        services = Services.objects.filter(
            Q(name__icontains=search_term) |
            Q(details__icontains=search_term),
            company__isPartner=True,
        ).order_by('-id')
        additional_query_string = f'&q={search_term}'

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    page_object, pagination_range = make_pagination(request, services, PER_PAGE)

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'additional_url_query': additional_query_string,
        'pagination_range': pagination_range,
        'products_amount': products_amount,
        'search_term': search_term,
        'services': page_object, 
        'user_profile': user_profile,
    }

    return render(request=request, template_name='main/pages/services.html', context=context)


@login_required(login_url='main_app:login', redirect_field_name='next')
def service(request, slug):

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'products_amount': products_amount,
        'user_profile': user_profile,
    }

    return render(request=request, template_name='main/pages/services.html', context=context)


@login_required(login_url='main_app:login', redirect_field_name='next')
def requests(request):

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    user_requests = Requests.objects.filter(
        owner=user_profile
    ).order_by('-id')    

    search_term = request.GET.get('q', '').strip()

    if user_profile.serviceTer != 'Nenhum':
        if not search_term:
            others_requests = Requests.objects.filter(
                ~Q(owner=user_profile),
                Q(concluded=False)
            ).order_by('-id')
            additional_query_string = ''
        else:
            others_requests = Requests.objects.filter(
                Q(name__icontains=search_term),
                ~Q(owner=user_profile),
                Q(concluded=False)
            ).order_by('-id')
            additional_query_string = f'&q={search_term}'
    
        page_object, pagination_range = make_pagination(request, others_requests, PER_PAGE)

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'additional_query_string': additional_query_string,
        'pagination_range': pagination_range,
        'others_requests': page_object,
        'products_amount': products_amount,
        'user_profile': user_profile,
        'user_requests': user_requests,
    }

    return render(request=request, template_name='main/pages/requests.html', context=context)


@login_required(login_url='main_app:login', redirect_field_name='next')
def request(request, slug):

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'products_amount': products_amount,
        'user_profile': user_profile,
    }

    return render(request=request, template_name='main/pages/request.html', context=context)


@login_required(login_url='main_app:login', redirect_field_name='next')
def company(request, slug):
    company = get_object_or_404(
        Companies, slug=slug
    )

    products = Products.objects.filter(
        company__id=company.id
    ).order_by('-id')

    services = Services.objects.filter(
        company__id=company.id
    ).order_by('-id')

    social_medias = SocialMedia.objects.filter(
        company__id=company.id
    ).order_by('-id')

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'company': company, 
        'products': products,
        'products_amount': products_amount,
        'services': services,
        'social_medias': social_medias,
        'user_profile': user_profile,
    }

    return render(request=request, template_name='main/pages/company.html', context=context)


@login_required(login_url='main_app:login', redirect_field_name='next')
def profile(request, slug):

    profile = get_object_or_404(
        UserProfile, user__username=slug
    )

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    companies_owned = Companies.objects.filter(
        owner__CPF=profile.CPF
    )

    companies_working = Employee.objects.filter(
        employee__CPF=profile.CPF
    )

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'companies_owned': companies_owned,
        'companies_working': companies_working,
        'products_amount': products_amount,

main_app/templates/main/pages/about-us.html
{% extends "main/base/base.html" %}

{% load static %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/about-us.css' %}">
{% endblock static %}

{% block title %}Sobre nós{% endblock title %}

{% block content %}
<img src="{% static "main/img/aboutImage.png" %}" class="about-image">


<div class="about-content">    
    <p>
        O conecta metal é uma inovadora plataforma concebida para simplificar o processo de aquisição de produtos na área de metalurgia. Diante da carência de um portal abrangente que congregasse diversas empresas do setor, reconhecemos a necessidade de preencher essa lacuna. Assim, decidimos criar o Conecta Metal, um projeto concebido por um grupo de seis estudantes do Entra21.
    </p>
    <p>
        Nosso objetivo é fornecer uma solução abrangente, reunindo empresas metalúrgicas e facilitando o acesso direto a seus produtos e serviços personalizados. Comprometemo-nos com a excelência, buscando incessantemente oferecer aos nossos clientes as melhores opções disponíveis no mercado. Nossa plataforma foi desenvolvida para atender às necessidades específicas de planejamento e aquisição de serviços exclusivos na área da metalurgia.
    </p>
    <p>
        Garantimos aos nossos clientes a facilidade na aquisição de produtos de alta qualidade, superando constantemente suas expectativas. Mais do que meramente comercializar, almejamos estabelecer parcerias sólidas entre clientes e empresas, fortalecendo assim o setor metalúrgico. Convidamos você a fazer parte dessa jornada conosco, onde nosso compromisso é conectar você ao que há de melhor no universo da metalurgia.
    </p>
    </div>
{% endblock content %}

main_app/templates/main/pages/cart.html
{% extends "main/base/base.html" %}

{% load static %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/cart.css' %}">
{% endblock static %}

{% block title %}Carrinho{% endblock title %}

{% block content %}
    <div class="cart-container">
        <div class="cart-list">
            <div class="cart-list-header">
                <h2 class="cart-header-product">Produto</h2>
                <h2 class="cart-header-amount">Quantidade</h2>
                <h2 class="cart-header-price">Preço Final</h2>
                <h2 class="cart-header-delete"> - </h2>
            </div>
            <div class="cart-list-items">
                {% for cart_product in cart_products %}
                    {% include "main/partials/cart-card.html" %}
                {% endfor %}
            </div>
        </div>
        <div class="cart-summary">
            <div class="cart-summary-info">
                <div class="cart-summary-title">
                    <h2>RESUMO DO PEDIDO</h2>
                </div>
                <div class="cart-summary-data">
                    <div class="cart-summary-separator"></div>
                    <p>Quantidade de Produtos: {{ products_amount }}</p>
                    <p>Valor dos Produtos: R$ {{ products_value }}</p>
                    <div class="cart-summary-separator"></div>
                    <p>Frete: R$ {{ products_freight }}</p>
                    <p>Valor Total: R$ {{ products_final_value }}</p>
                    <div class="cart-summary-separator"></div>
                </div>
                <div class="cart-summary-next">
                    <button type="submit" class="cart-summary-submit"><h2>Continuar</h2></button>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

main_app/templates/main/pages/dashboard.html
{% extends "main/base/base.html" %}

{% load static %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/dashboard.css' %}">
{% endblock static %}

{% block title %}Painel de Controle{% endblock title %}

{% block content %}
    <div class="dashboard-container">
        <div class="dashboard-title">
            <div class="dashboard-title-left">
                <div class="dashboard-new-company">
                    <a href="{% url "main_app:company_view" %}">
                        <i class="fa-solid fa-plus"></i>
                        <h2>Adicionar Empresa</h2>
                    </a>
                </div>
            </div>
            <h1>Suas Empresas</h1>
            <div class="dashboard-title-right"></div>
        </div>
        <div class="dashboard-content">
            {% for company in user_companies %}
                {% include "main/partials/dashboard-company-card.html" %}
            {% endfor %}
        </div>
    </div>
{% endblock content %}

main_app/templates/main/pages/historic.html
{% extends "main/base/base.html" %}

{% load static %}

{% block static %}
    
{% endblock static %}

{% block title %}Histórico de Compras{% endblock title %}

{% block content %}
    
{% endblock content %}

main_app/templates/main/pages/home.html
{% extends "main/base/base.html" %}

{% block styles %}{% endblock styles %}

{% block title %}Início{% endblock title %}

{% block content %}
    {% include "main/partials/search.html" %}
    {% include "main/partials/home-products.html" %}
{% endblock content %}

main_app/templates/main/pages/login.html
{% extends "main/base/base.html" %}

{% load static %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/form.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/login.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/message.css' %}">
{% endblock static %}

{% block title %}Cadastrar{% endblock title %}

{% block content %}
    <div class="form-container">
        <div class="form-content">
            <h2>Entrar</h2>
            <form action="{% url "main_app:validate" %}" method="POST">
                {% csrf_token %}

                {% include "main/partials/form.html" %}

                {% include 'main/partials/messages.html' %}

                <div class="form-item form-button">
                    <button type="submit">Entrar</button>
                </div>
            </form>
        </div>
    </div>
    
{% endblock content %}


main_app/templates/main/pages/product.html
{% extends "main/base/base.html" %}

{% block title %}Produto | {{ product.name }}{% endblock title %}

{% block content %}
    <div class="product-container">
        <div class="product-cover">
            <div class="product-options">
                <button onclick="changePicture('{{ product.mainPicture.url }}')">
                    <img src="{{ product.mainPicture.url }}" alt="">
                </button>
                {% if product.secondPicture %}
                    <button onclick="changePicture('{{ product.secondPicture.url }}')">
                        <img src="{{ product.secondPicture.url }}" alt="">
                    </button>
                {% endif %}
                {% if product.thirdPicture %}
                    <button onclick="changePicture('{{ product.thirdPicture.url }}')">
                        <img src="{{ product.thirdPicture.url }}" alt="">
                    </button>
                {% endif %}
                {% if product.fourthPicture %}
                    <button onclick="changePicture('{{ product.fourthPicture.url }}')">
                        <img src="{{ product.fourthPicture.url }}" alt="">
                    </button>
                {% endif %}
            </div>
            <div class="product-img">
                <img id="picture-container" src="{{ product.mainPicture.url }}" class="product-cover-img">
            </div>
        </div>

        <div class="product-info">
            <div class="product-title">
                <h1>{{ product.name }}</h1>
            </div>
            <div class="product-owner">
                <a href="{% url 'main_app:company' product.company.slug %}">
                    <img src="{{ product.company.profilePic.url }}" alt="">
                    {{ product.company.businessName }}
                </a>
            </div>
        </div>

        <div class="product-value">
            <h2>R$ {{ product.value }}</h2>
        </div>

        <div class="product-description">
            {{ product.description }}
        </div>

        <div class="product-rating">
            {% include "main/partials/product-rating.html" %}
        </div>

        <div class="product-button">
            <form action="{% url "main_app:product" product.slug %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="client" value="{{ user_profile.id }}">
                <input type="hidden" name="product" value="{{ product.id }}">
                <input type="hidden" name="amount" value=1>
                <input type="hidden" name="finalPrice" value={{ 0 }}>
                <button type="submit"><i class="fa-solid fa-cart-shopping"></i> Comprar</button>
            </form>
        </div>
    </div>
{% endblock content %}

main_app/templates/main/pages/profile.html
{% extends "main/base/base.html" %}

{% load static %}

{% block static %}
    <script src="{% static "main/js/script.js" %}"></script>
    <link rel="stylesheet" href="{% static 'main/css/profile.css' %}">
{% endblock static %}

{% block title %}{{ profile.user.username }}{% endblock title %}

{% block content %}
    <div class="profile-container">

        <div class="profile-identification">
            <div class="profile-picture {{ profile.serviceTer }}">
                {% if profile.picture %}
                    <img src="{{ profile.picture.url }}" alt="">
                {% else %}
                    <img src="{% static "main/img/no_profile_picture.png" %}" alt="">
                {% endif %}
            </div>
            <div class="profile-info">
                <div class="profile-names">
                    <h1 class="profile-name">{{ profile.user.first_name }} {{ profile.user.last_name }}</h1>
                    <h2 class="profile-username">@{{ profile.user.username }}</h2>
                </div>
                <div class="profile-email">
                    <i class="fa-solid fa-envelope"></i> E-mail: {{ profile.user.email }}
                </div>
                {% if profile.phone %}
                    <div class="profile-phone">
                        <i class="fa-solid fa-phone"></i> Contato: {{ profile.phone }}
                    </div>
                {% endif %}
                {% if companies_working %}
                    <div class="profile-companies">
                        {% for company in companies_working %}
                            <p>Funcionário da empresa <a href="{% url "main_app:company" company.company.slug %}">{{ company.company.businessName }}</a></p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
                <div class="profile-buttons">
                    <button class="profile-share">
                        <i class="fa-solid fa-share-nodes"></i>
                    </button>
                    <a class="profile-message" href="https://wa.me/{{ profile.phone }}?text=Olá, vi seu perfil no Conecta Metal." target="_blank">
                        <i class="fa-solid fa-message"></i>
                    </a>
                    <button class="profile-report" onclick="reportUser('{{ profile.user.username }}')">
                        <i class="fa-solid fa-flag"></i>
                    </button>
                </div>
            
        </div>  
    </div>

    {% if profile.aboutMe %}
        <div class="profile-container profile-repeat">
            <div class="profile-about">
                <h2>Sobre mim:</h2>
                <p>{{ profile.aboutMe }}</p>
            </div>
        </div>
    {% endif %}

    {% if companies_owned %}
        <div class="profile-container profile-repeat">
            <div class="profile-owned">
                <h2 class="profile-owned-title">Empresas Gerenciadas pelo Usuário</h2>
                <div class="profile-company-list">
                    {% for company in companies_owned %}
                        {% include "main/partials/profile-company-card.html" %}
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}


main_app/templates/main/pages/register-company.html
{% extends "main/base/base.html" %}

{% load static %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/form.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/register-company-form.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/message.css' %}">
{% endblock static %}

{% block title %}Cadastrar Empresa{% endblock title %}

{% block content %}
    <div class="form-container">
        <div class="form-content">
            <h2>Cadastrar Empresa</h2>
            <form action="{% url "main_app:company_create" %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% include "main/partials/form.html" %}

                {% include 'main/partials/messages.html' %}

                <div class="form-item form-button">
                    <button type="submit">Enviar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

main_app/templates/main/pages/register.html
{% extends "main/base/base.html" %}

{% load static %}

{% block static %}
    <link rel="stylesheet" href="{% static 'main/css/form.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/register-company.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/message.css' %}">
{% endblock static %}

{% block title %}Cadastrar{% endblock title %}

{% block content %}
    <div class="form-container">
        <div class="form-content">
            <h2>Criar Conta</h2>
            <form action="{% url "main_app:create" %}" method="POST">
                {% csrf_token %}

                {% include "main/partials/form.html" %}

                {% include 'main/partials/messages.html' %}

                <div class="form-item form-button">
                    <button type="submit">Enviar</button>
                </div>
            </form>
        </div>
    </div>
    
{% endblock content %}
