main_app/urls.py
from django.urls import path
from . import views

app_name = 'main_app'

urlpatterns = [
    # Main paths
    path('', views.home, name="home"),
    path('product/<slug:slug>/', views.product, name="product"),
    path('service/', views.services, name="services"),
    path('service/<slug:slug>/', views.service, name="service"),
    path('requests/', views.requests, name="requests"),
    path('requests/<slug:slug>', views.request, name="request"),

    # Company Register Paths
    path('dashboard/company/', views.register_company_view, name="company_view"),
    path('dashboard/company/create', views.register_company_create, name="company_create"),

    # Profile paths
    path('company/<slug:slug>/', views.company, name="company"),
    path('profile/<slug:slug>/', views.profile, name="profile"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('historic/', views.historic, name="historic"),

    # Shopping Cart paths
    path('shopping/', views.shopping_cart, name="shopping"),
    path('shopping/delete', views.shopping_delete, name="shopping_delete"),
    path('shopping/edit', views.shopping_edit, name="shopping_edit"),
    
    # Register / Login / Logout paths
    path('register/', views.register_view, name="register"),
    path('register/create/', views.register_create, name="create"),
    path('login/', views.login_view, name="login"),
    path('login/validate', views.login_validate, name='validate'),
    path('logout/', views.logout_view, name="logout"),

    # Other paths
    path('about/', views.about_us, name="about"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_app/forms/add_to_cart.py
from django import forms
from ..models import ShoppingCart

class AddToCartForm(forms.ModelForm):
    
    class Meta:
        model = ShoppingCart
        fields = ("client", "product", "amount", "finalPrice")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)





main_app/forms/login.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(
        label='Usuário',
        widget=forms.TextInput(attrs={
            'placeholder': 'Insira seu nome de usuário'
        })
    )
    password = forms.CharField(
        label='Senha',
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Insira sua senha'
        })
    )

main_app/forms/register_company.py
import requests
from django import forms
from ..models import Companies, Address, UserProfile
from django.core.exceptions import ValidationError
from utils import form_utils as fu
import PIL


class RegisterCompanyForm(forms.Form):

    # Company Fields
    CNPJ = forms.CharField(
        label='CNPJ',
        validators=[fu.valid_cnpj],
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Ex.: "01.234.567/8910-11."'
            }
        )
    )
    legalName = forms.CharField(
        label='Razão Social',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Razão social da empresa'
            }
        )
    )
    businessName = forms.CharField(
        label='Nome Fantasia',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Nome fantasia da empresa'
            }
        )
    )

    # Address Fields
    CEP = forms.CharField(
        label='CEP',
        validators = [fu.valid_cep],
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Ex.: "12345-678"'
            }
        )
    )
    number = forms.IntegerField(
        label='Número',
        widget=forms.NumberInput(
            attrs={
                'placeholder': 'Número do endereço'
            }
        )
    )
    complement = forms.CharField(
        label='Complemento',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Complemento do endereço'
            }
        )
    )

    # More Company Fields
    description = forms.CharField(
        label='Descrição',
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Descrição da empresa'
            }
        )
    )
    profilePic = forms.ImageField(
        label='Foto de Perfil',
        required=False,
        widget=forms.FileInput()
    )

    def clean_CNPJ(self):
        data = self.cleaned_data.get('CNPJ')
        url = f"https://publica.cnpj.ws/cnpj/{fu.clear_data(data)}"
        response = requests.get(url)

        if response.status_code != 200:
            raise ValidationError(
                'CNPJ inválido',
                code='invalid'
            )

        return fu.clear_data(data)
    
    def clean_CEP(self):
        data = self.cleaned_data['CEP']
        data = fu.clear_data(data)
        url = f'https://viacep.com.br/ws/{data}/json/'
        response = requests.get(url)

        if response.status_code != 200:
            raise ValidationError('Tente novamente mais tarde')
        
        if 'erro' in response.json():
            raise ValidationError(
                'CEP inválido',
                code='invalid'
            )

        return data
    
    def save(self, user):
        cep = self.cleaned_data['CEP']
        number = str(self.cleaned_data['number'])
        complement = self.cleaned_data['complement']
        address = Address.objects.filter(
            CEP=cep,
            number=number,
            complement=complement
        ).first()

        if not address:
            url = f'https://viacep.com.br/ws/{cep}/json/'
            response = requests.get(url).json()

            address = Address.objects.create(
                CEP=cep,
                state=response['uf'],
                city=response['localidade'],
                neigborhood=response['bairro'],
                streetAddress=response['logradouro'],
                number=number,
                complement=complement
            )

        cnpj = self.cleaned_data['CNPJ']
        legal_name = self.cleaned_data['legalName']
        business_name = self.cleaned_data['businessName']
        profile_pic = self.cleaned_data['profilePic']
        description = self.cleaned_data['description']
        
        company = Companies.objects.create(
            CNPJ=cnpj,
            legalName=legal_name,
            businessName=business_name,
            slug=fu.create_slug(legal_name),
            profilePic=profile_pic,
            description=description,
            owner=user,
            address=address,
            isPartner=True,
        )
        print('salvei')

        return company


main_app/views.py
from django.http.response import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.models import User
from main_app.models import Products, Companies, SocialMedia, Services, UserProfile, ShoppingCart, Employee, Requests
from utils.pagination import make_pagination
from .forms import LoginForm, SignUpForm, AddToCartForm, RegisterCompanyForm

import os

PER_PAGE = int(os.environ.get('PER_PAGE', 30))

# Create your views here.
@login_required(login_url='main_app:login', redirect_field_name='next')
def home(request):

    search_term = request.GET.get('q', '').strip()

    if not search_term:
        products = Products.objects.filter(
            company__isPartner=True
        ).order_by('-id')
        additional_query_string = ''
    else:
        products = Products.objects.filter(
            Q(name__icontains=search_term) |
            Q(details__icontains=search_term),
            company__isPartner=True,
        ).order_by('-id')
        additional_query_string = f'&q={search_term}'

    if request.method == 'POST':
        form = AddToCartForm(request.POST)
        if form.is_valid():
            existing_item = ShoppingCart.objects.filter(
                client=form.cleaned_data['client'],
                product=form.cleaned_data['product']
            ).exists()
            if not existing_item:
                form.save()
    else:
        form = AddToCartForm()
    form = AddToCartForm()

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    page_object, pagination_range = make_pagination(request, products, PER_PAGE)

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'additional_url_query': additional_query_string,
        'form': form,
        'pagination_range': pagination_range,
        'products': page_object, 
        'products_amount': products_amount,
        'search_term': search_term,
        'show_products': True,
        'user_profile': user_profile,
    }

    return render(request=request, template_name='main/pages/home.html', context=context)


@login_required(login_url='main_app:login', redirect_field_name='next')
def product(request, slug):
    product = get_object_or_404(
        Products, slug=slug
    )

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    if request.method == 'POST':
        form = AddToCartForm(request.POST)
        if form.is_valid():
            existing_item = ShoppingCart.objects.filter(
                client=form.cleaned_data['client'],
                product=form.cleaned_data['product']
            ).exists()
            if not existing_item:
                form.save()
    else:
        form = AddToCartForm()

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'form': form,
        'product': product,
        'products_amount': products_amount,
        'user_profile': user_profile,
        }

    return render(request=request, template_name='main/pages/product.html', context=context)


@login_required(login_url='main_app:login', redirect_field_name='next')
def services(request):

    search_term = request.GET.get('q', '').strip()

    if not search_term:
        services = Services.objects.filter(
            company__isPartner=True
        ).order_by('-id')
        additional_query_string = ''
    else:
        services = Services.objects.filter(
            Q(name__icontains=search_term) |
            Q(details__icontains=search_term),
            company__isPartner=True,
        ).order_by('-id')
        additional_query_string = f'&q={search_term}'

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    page_object, pagination_range = make_pagination(request, services, PER_PAGE)

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'additional_url_query': additional_query_string,
        'pagination_range': pagination_range,
        'products_amount': products_amount,
        'search_term': search_term,
        'services': page_object, 
        'user_profile': user_profile,
    }

    return render(request=request, template_name='main/pages/services.html', context=context)


@login_required(login_url='main_app:login', redirect_field_name='next')
def service(request, slug):

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'products_amount': products_amount,
        'user_profile': user_profile,
    }

    return render(request=request, template_name='main/pages/services.html', context=context)


@login_required(login_url='main_app:login', redirect_field_name='next')
def requests(request):

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    user_requests = Requests.objects.filter(
        owner=user_profile
    ).order_by('-id')    

    search_term = request.GET.get('q', '').strip()

    if user_profile.serviceTer != 'Nenhum':
        if not search_term:
            others_requests = Requests.objects.filter(
                ~Q(owner=user_profile),
                Q(concluded=False)
            ).order_by('-id')
            additional_query_string = ''
        else:
            others_requests = Requests.objects.filter(
                Q(name__icontains=search_term),
                ~Q(owner=user_profile),
                Q(concluded=False)
            ).order_by('-id')
            additional_query_string = f'&q={search_term}'
    
        page_object, pagination_range = make_pagination(request, others_requests, PER_PAGE)

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'additional_query_string': additional_query_string,
        'pagination_range': pagination_range,
        'others_requests': page_object,
        'products_amount': products_amount,
        'user_profile': user_profile,
        'user_requests': user_requests,
    }

    return render(request=request, template_name='main/pages/requests.html', context=context)


@login_required(login_url='main_app:login', redirect_field_name='next')
def request(request, slug):

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'products_amount': products_amount,
        'user_profile': user_profile,
    }

    return render(request=request, template_name='main/pages/request.html', context=context)


@login_required(login_url='main_app:login', redirect_field_name='next')
def company(request, slug):
    company = get_object_or_404(
        Companies, slug=slug
    )

    products = Products.objects.filter(
        company__id=company.id
    ).order_by('-id')

    services = Services.objects.filter(
        company__id=company.id
    ).order_by('-id')

    social_medias = SocialMedia.objects.filter(
        company__id=company.id
    ).order_by('-id')

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'company': company, 
        'products': products,
        'products_amount': products_amount,
        'services': services,
        'social_medias': social_medias,
        'user_profile': user_profile,
    }

    return render(request=request, template_name='main/pages/company.html', context=context)


@login_required(login_url='main_app:login', redirect_field_name='next')
def profile(request, slug):

    profile = get_object_or_404(
        UserProfile, user__username=slug
    )

    user_profile = UserProfile.objects.filter(
        user=request.user
    ).first()

    cart_products = ShoppingCart.objects.filter(
        client__user = request.user
    ).order_by('-id')

    companies_owned = Companies.objects.filter(
        owner__CPF=profile.CPF
    )

    companies_working = Employee.objects.filter(
        employee__CPF=profile.CPF
    )

    products_amount = 0
    for cart_product in cart_products:
        products_amount += cart_product.amount

    context = {
        'companies_owned': companies_owned,
        'companies_working': companies_working,
        'products_amount': products_amount,

main_app/templates/main/partials/card.html
<div class="card main-content-list-item">
    <a href="product/">
        <div class="card-cover">
            <img src="{{ product.picture.url }}" alt="">
        </div>

        <div class="card-title">
            <h2>{{ product.name }}</h2>
        </div>

        <div class="card-value">
            R$ {{ product.value }}
        </div>

        <div class="card-details">
            <p>{{ product.details }}</p>
        </div>

        <div class="card-info">
            <div class="card-rating">
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-regular fa-star-half-stroke"></i>
                <i class="fa-regular fa-star"></i>
                <i class="fa-regular fa-star"></i>
            </div>

            <div class="card-owner">
                <i class="fa-solid fa-user"></i>
                {{ product.company.businessName }}
            </div>
        </div>
    </a>
    <div class="card-button">
        <button><i class="fa-solid fa-cart-shopping"></i> Comprar</button>
    </div>
</div>

main_app/templates/main/partials/cart-card.html
<div class="cart-card-container">
    <div class="cart-card-product">
        <a href="{% url "main_app:product" cart_product.product.slug %}">
            <div class="cart-card-cover">
                <img src="{{ cart_product.product.mainPicture.url }}" alt="">
            </div>
            <div class="cart-card-title">
                <h2>{{ cart_product.product.name }}</h2>
            </div>
        </a>
    </div>
    <div class="cart-card-amount">
        <form action="{% url "main_app:shopping_edit" %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="cart_item_id" value="{{ cart_product.id }}">
            <input type="hidden" name="type" value="decrease">
            <button class="cart-amount-less cart-amount-button"><i class="fa-solid fa-angle-left"></i></button>
        </form>
        <p class="cart-amount-button">{{ cart_product.amount }}</p>
        <form action="{% url "main_app:shopping_edit" %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="cart_item_id" value="{{ cart_product.id }}">
            <input type="hidden" name="type" value="raise">
            <button class="cart-amount-plus cart-amount-button"><i class="fa-solid fa-angle-right"></i></button>
        </form>
    </div>
    <div class="cart-card-price">
        <p>R$ {{ cart_product.finalPrice }}</p>
    </div>
    <div class="cart-card-delete">
        <form action="{% url "main_app:shopping_delete" %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="cart_item_id" value="{{ cart_product.id }}">
            <button class="cart-amount-button"><i class="fa-solid fa-xmark"></i></button>
        </form>
        
    </div>
</div>

main_app/templates/main/partials/company-card.html
<div class="main-company-card-container">
    <a href="{% url 'main_app:product' product.slug %}">
        <img src="{{ product.picture.url }}" alt="">
    </a>
</div>

main_app/templates/main/partials/company-rating.html
{% if company.rating > 4.75 %}
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
{% elif company.rating > 4.25 %}
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-regular fa-star-half-stroke"></i>
{% elif company.rating > 3.75 %}
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-regular fa-star"></i>
{% elif company.rating > 3.25 %}
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-regular fa-star-half-stroke"></i>
    <i class="fa-regular fa-star"></i>
{% elif company.rating > 2.75 %}
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
{% elif company.rating > 2.25 %}
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-regular fa-star-half-stroke"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
{% elif company.rating > 1.75 %}
    <i class="fa-solid fa-star"></i>
    <i class="fa-solid fa-star"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
{% elif company.rating > 1.25 %}
    <i class="fa-solid fa-star"></i>
    <i class="fa-regular fa-star-half-stroke"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
{% elif company.rating > 0.75 %}
    <i class="fa-solid fa-star"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
{% elif company.rating > 0.25 %}
    <i class="fa-regular fa-star-half-stroke"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
{% else %}
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
    <i class="fa-regular fa-star"></i>
{% endif %}

main_app/templates/main/partials/footer.html
<footer class="main-footer-container">
    <div class="main-footer-info">
        <div class="main-footer-socials">
            <a href="https://x.com/ConectaMetal?s=20"><i class="fa-brands fa-x-twitter"></i></a>
            <a href="https://www.instagram.com/conecta.metal/?igsh=MW15bGNhcTVsNDQyZg%3D%3D"><i class="fa-brands fa-instagram"></i></a>
            <a href="https://linkedin.com/in/conecta-metal-57ba872b4"><i class="fa-brands fa-linkedin"></i></a>
            <a href="https://github.com/ConectaMetal"><i class="fa-brands fa-github"></i></a>
            <a href="conectametal@gmail.com"><i class="fa-solid fa-envelope"></i></a>
        </div>
        <div class="main-footer-about-us">
            <a class="main-footer-button" href="{% url "main_app:about" %}">Sobre Nós</a>
        </div>
    </div>
    <div class="main-footer-rights">
        ©2024 - Conecta Metal. Todos os direitos reservados.
    </div>
</footer>

main_app/templates/main/partials/home-products.html
<div class="main-products-container">
    <div class="main-products-option">
        <button class="main-products-option-button" name="products">Produtos</button>
        <button class="main-products-option-button" name="services">Serviços</button>
    </div>
    <div class="main-products-list">
        {% for product in products %}
            {% include "main/partials/products-card.html" %}
        {% endfor %}
    </div>
    {% include "main/partials/pagination.html" %}
</div>

main_app/templates/main/partials/pagination.html
<div class="pagination-container">
    <div class="pagination-content">
        {% if pagination_range.current_page != 1 %}
            <a href="?page=1{{ additional_url_query }}" class="pagination-link pagination-item"><i class="fa-solid fa-angles-left"></i></a>
            <a href="?page={{ pagination_range.prev_page }}{{ additional_url_query }}" class="pagination-link pagination-item"><i class="fa-solid fa-angle-left"></i></a>
        {% endif %}

        {% for page in pagination_range.pagination %}
            {% if pagination_range.current_page == page %}
                <a href="?page={{ page }}{{ additional_url_query }}" class="pagination-link pagination-item pagination-current">{{ page }}</a>
            {% else %}
                <a href="?page={{ page }}{{ additional_url_query }}" class="pagination-link pagination-item">{{ page }}</a>
            {% endif %}
        {% endfor %}

        {% if pagination_range.current_page != pagination_range.total_pages %}
            <a href="?page={{ pagination_range.next_page }}{{ additional_url_query }}" class="pagination-link pagination-item"><i class="fa-solid fa-angle-right"></i></a>
            <a href="?page={{ pagination_range.total_pages }}{{ additional_url_query }}" class="pagination-link pagination-item"><i class="fa-solid fa-angles-right"></i></a>
        {% endif %}
        
    </div>
</div>

main_app/templates/main/partials/product-card.html
<div class="card main-content-list-item">
    <a href="product/{{ product.slug }}">
        <div class="card-cover">
            <img src="{{ product.picture.url }}" alt="">
        </div>

        <div class="card-title">
            <h2>{{ product.name }}</h2>
        </div>

        <div class="card-value">
            R$ {{ product.value }}
        </div>

        <div class="card-details">
            <p>{{ product.details }}</p>
        </div>
    </a>
        <div class="card-info">
            <div class="card-rating">
                {% include "main/partials/products-rating.html" %}
            </div>

            <div class="card-owner">
                <a href="{% url 'main_app:company' product.company.slug %}">
                    <img src="{{ product.company.profilePic.url }}" alt="">
                    {{ product.company.businessName }}
                </a>
            </div>
        </div>
    <div class="card-button">
        <button><i class="fa-solid fa-cart-shopping"></i> Comprar</button>
    </div>
</div>

main_app/templates/main/partials/products-card.html
<div class="card main-content-list-item">
    <a href="product/{{ product.slug }}">
        <div class="card-cover">
            <img src="{{ product.mainPicture.url }}" alt="">
        </div>

        <div class="card-title">
            <h2>{{ product.name }}</h2>
        </div>

        <div class="card-value">
            R$ {{ product.value }}
        </div>

        <div class="card-details">
            <p>{{ product.details }}</p>
        </div>
    </a>
        <div class="card-info">
            <div class="card-rating">
                {% include "main/partials/product-rating.html" %}
            </div>

            <div class="card-owner">
                <a href="{% url 'main_app:company' product.company.slug %}">
                    <img src="{{ product.company.profilePic.url }}" alt="">
                    {{ product.company.businessName }}
                </a>
            </div>
        </div>
    <div class="card-button">
        <form action="{% url "main_app:home" %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="client" value="{{ user_profile.id }}">
            <input type="hidden" name="product" value="{{ product.id }}">
            <input type="hidden" name="amount" value={{ 1 }}>
            <input type="hidden" name="finalPrice" value={{ 0 }}>
            <button type="submit"><i class="fa-solid fa-cart-shopping"></i> Comprar</button>
        </form>
    </div>
</div>

main_app/templates/main/partials/products.html
<div class="main-products-container">
    <div class="main-products-option">
        <button class="main-products-option-button" name="products">Produtos</button>
        <button class="main-products-option-button" name="services">Serviços</button>
    </div>
    <div class="main-products-list">
        {% for product in products %}
            {% include "main/partials/product-card.html" %}
        {% endfor %}
    </div>
</div>

main_app/templates/main/partials/profile-company-card.html
<div class="profile-company-card">
    <a href="{% url "main_app:company" company.slug %}">
        <div class="company-card-cover">
            <img src="{{ company.profilePic.url }}" alt="">
        </div>
        <div class="company-name">
            <h2>{{ company.businessName }}</h2>
        </div>
    </a>
</div>

main_app/templates/main/partials/requests-card.html
<div class="requests-card">
    <div class="requests-card-content">
        <div class="request-card-title">
            <a href="#">
                <h2>{{ request.name }}</h2>
            </a>
        </div>
        <div class="request-card-info">
            <div class="request-card-budget">
                <h4>Orçamento: R$ {{ request.maxBudget }}</h3>
            </div>
            <div class="request-card-type">
                <h4>Tipo: {{ request.type }}</h3>
            </div>
            <div class="request-card-owner">
                <a href="{% url "main_app:profile" request.owner.user.username %}">
                    {% if request.owner.picture %}
                        <img src="{{ request.owner.picture.url }}" alt="">
                    {% endif %}
                    <h4>{{ request.owner.user.username }}</h4>
                </a>
            </div>
        </div>
    </div>
    {% if user_profile == request.owner %}
        <div class="requests-card-button">
            <button>
                <i class="fa-solid fa-pen-to-square"></i>
            </button>
        </div>
    {% endif %}
</div>

main_app/templates/main/partials/search.html
<div class="search-container">
    <div class="search-bar">
        <button class="search-filter"><i class="fa-solid fa-sliders"></i></button>
        <form action="" class="search-form">
            <input type="search" class="search-input" name="q" value="{{ search_term }}" required>
            <button type="submit" class="search-button"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
    </div>
</div>